:PROPERTIES:
:ID:       8dbcae8e-77f5-4f68-8add-d8bf09fd56c9
:END:
#+title: Matèrn covariance

* Définitions

Il nous faut définir une fonction de [[id:5fad86fa-b6e9-4803-b4be-e9ccb6804cdc][covariance]] particulière afin d'écrire la fonction de 'likelihood' nous permettant d'estimer de paramètres. C'est le rôle de la famille de fonctions de Matèrn.

La covariance est simplement la variance si elle ne varie pas dans l'espace elle peut donc être noté $\sigma^{2}$.

$$C(d) = \sigma^{2} p(d), \quad d > 0$$

$p(d)$ est la fonction de corrélation. Quand $d = 0$ la covariance est la même que la variance et donc $C(d) = \sigma^{2}$. Le but est donc que $p(d) \rightarrow 1$ alors $d \rightarrow 0$. La fonction de corrélation doit décroître à mesure que la distance augmente.

#+BEGIN_QUOTE
Everything is related to everything else, but near things are more related than distant things (Tobler 1970)
#+END_QUOTE

Il faut cependant faire attention à ne pas obtenir de variance négative.

La valeur de $d$, posons $d_{0}$ qui permet de résoudre $p(d) = 0$ est appelé la porté (/range/). La fonction de corrélation est monotone et ne peut donc pas remonter une fois le 0 atteins. Dans certains cas il n'est pas possible d'atteindre le 0 on va donc par convention à 0.05 que l'on nome portée effective (/effective range/).


Cette famille de fonction est définie ainsi:

$$C(d|\psi) = \sigma^{2} p(d|v)$$

Où:

$$p(d|v) = \frac{1}{2^{v-1}} (\sqrt{2v}\phi d )^{v} K_{v} (\sqrt{2v}\phi d), \quad \phi > 0, v > 0, d > 0$$


Avec:

$$\psi = (\sigma^{2}, v)$$

Et:

$$v = (\phi, \mu)$$

$\Gamma(\mu)$ represente la fonction gamma et $K_{v}(.)$ correspond à la fonction modifiée de Bessel avec un degrée de \mu.

Ainsi $C(d|\psi)$ ne dépend que de $\mu$ et $\phi$.

$\mu$ correspond à la /smouthness/ de la covariance et $\phi$ à la décroissance lorsque de $d$ diminue.


Si $\mu$ augmente alors plus c'est "lisse", le maximum étant le cas de type $y(s) = a + bx(s)$ qui n'ont besoin que de deux points pour être obtenu et forme une ligne droite.

*** Cas particuliers

- si $\mu = \frac{1}{2}$ alors $C(d|\psi) = \sigma^{2} exp(-\phi d)$ qui correspond à une fonction exponentielle de la covariance. On a donc $p(d|\phi) = exp(-\phi d)$ mais on ne peut pas atteindre 0 et il faut donc le remplacer par 0.05:

  Pour une distance de 10km  $exp = (-\phi d) = 0.05$ donc $-log(0.05)/\phi = d$ soit $3/\phi$ ce qui permet d'obtenir un \phi = 0.3.

- Si $\mu = \frac{3}{2}$ alors $C(d|\psi) = \sigma^{2} (1 + \phi d )exp(-\phi d)$ ce qui est un peu plus lisse

- Si \mu tend vers l'infini alors la corrélation se poruisuit à de grande distance.

* Exemples:

#+begin_src R :results output :session *R* :exports both

library(bmstdr)
library(ggplot2)
library(akima)
library(tidyr)
library(RColorBrewer)
library(ggpubr)

set.seed(44)
n <- 500
x1 <- matrix(runif(2 * n), ncol = 2)
d <- as.matrix(dist(x1))
dim(d)

iidnormals <- rnorm(n)

covmat <- materncov(d, phi = 2, nu = 0.5 )

v <- exp(-d)

L <- chol(covmat)
dim(L)

y <- L %*% iidnormals
y <- scale(y, center = mean(y), scale=sd(y))
summary(y)

dplot <- data.frame(x=x1[,1], y=x1[,2], z=y)

xo <- seq(from=0, to =1, length=400)
yo <- seq(from=0, to =1, length=400)
surf <- interp(dplot$x, dplot$y, dplot$z,  xo=xo, yo=yo)

names(surf)
## [1] "x" "y" "z"
v <- list(x=surf$x, y=surf$y, z=surf$z)
# v <- fnc.delete.map.XYZ(xyz=surf)

interp1 <- data.frame(long = v$x, v$z )
names(interp1)[1:length(v$y)+1] <- v$y
interp1 <- gather(interp1,key = lat,value = field, -long,convert = TRUE)
com <- rev(c("firebrick4","firebrick2","white","dodgerblue2","dodgerblue4"))#colour palette
zr <- range(interp1$field, na.rm=T)

P <- ggplot() +
  geom_raster(data=interp1, aes(x = long, y = lat,fill = field)) +
  scale_fill_gradientn(colours=com, na.value="gray95", limits=zr)   +
  stat_contour(data=na.omit(interp1), aes(x = long, y = lat,z = field), colour = "black", binwidth =0.4) +
   theme(axis.text = element_blank(), axis.ticks = element_blank(), legend.position = "none") +
  labs(title= "Matern field with nu=0.5", x="", y="")
P

#+end_src

#+RESULTS:
#+begin_example
[1] 500 500
[1] 500 500
       V1
 Min.   :-8.877075
 1st Qu.:-0.303878
 Median : 0.008138
 Mean   : 0.000000
 3rd Qu.: 0.316981
 Max.   : 5.812364
[1] "x" "y" "z"
#+end_example

* Exo chap2

** Exo 1

Graph des différentes valeures de \phi et \mu pour les fonctions de corrélations de Matèrn.


#+begin_src R :results output :session *R* :exports both
library(ggplot2)

    d <- seq(from = 0.001, to = 3, length = 100)

mat1_exp <- maternfun(d, phi = 1, nu = 0.5)
mat1_15 <- maternfun(d, phi = 1, nu = 1.5)
mat1_25 <- maternfun(d, phi = 1, nu = 2.5)
mat1_35 <- maternfun(d, phi = 1, nu = 3.5)

k <- length(d)
unew <- data.frame(distance=rep(d, 4),
                   Matern=c(rep("Exponential", k), rep("nu = 1.5", k),  rep("nu = 2.5", k), rep("nu = 3.5", k)),
                   corr = c(mat1_exp, mat1_15, mat1_25, mat1_35))
unew$Matern <- factor(unew$Matern, levels=c("Exponential", "nu = 1.5", "nu = 2.5", "nu = 3.5"))
unew$variog <- 1-unew$corr

p0 <- ggplot() +
  geom_line(data=unew, aes(x=distance, y=corr, group=Matern, color=Matern, linetype=Matern), size=1.2) +
  labs(title= "Matern correlation function", x="Distance", y="Correlation")

p0
#+end_src

#+RESULTS:

#+begin_src R :results output :session *R* :exports both
p1 <- ggplot() +
  geom_line(data=unew, aes(x=distance, y=variog, group=Matern, color=Matern, linetype=Matern), size=1.2) +
  labs(title= "Matern Variogram", x="Distance", y="Variogram")

p1
#+end_src

#+RESULTS:
