:PROPERTIES:
:ID:       dcc375e2-2f99-4940-a6b2-3cca1e5e2f30
:END:
#+title: python

C'est mon pot pourri pour Python

* Opérateur de comparaisons

Comment deux valeurs se comparent et renvoie un booleens

Python permet aussi des comparaison de strings, par contre ce n'est pas possible de comparer deux objet de nature différente.

~"bill" < "bob"~ renvoie TRUE

*** and

return True si les deux sont True sinon False


*** or

seulement False or False renvoie False les autres combinaisons renvoient True

*** not

retourne l'opposé

Il y a des fonctions particulière pour travailler sur [[id:8c4cd16e-6661-432d-a681-7dfbd5bcc62a][numpy]]

* Structure de données

La fonction ~type~ renvoie le type de l'objet

** List

#+begin_src python
dude = ['bill', 'bob']
taille_m = [1.70, 1.85]

ind_bob = dude.index('bob')
# index est une méthode qui renvoie l'index d'un objet

return taille_m[ind_bob]

#+end_src

#+RESULTS:
: 1.85

Python commence à indexer à 0

Une trick pas mal pour retourner la dernière valeur: ~[-1]~

** Dictionaries

C'est un système de key:value mais il ne peut pas y avoir plus d'un type de clef. Cela ne fait pas sens que bill est plusieurs taille. Les keys sont "immutables" à la différence des listes mais on peut changer des valeurs.

#+begin_src python
taille = {"bill":1.70, "bob":1.85}

return taille["bill"]

#+end_src

#+RESULTS:
: 1.7

La *méthode* ~keys()~ renvoie les clés ie ~taille.keys()~

On peut ajouter des clefs: ~taille['jim'] = 1.54~

On peut supprimer une paire avec ~del(dico["key"])~

A la différence d'une liste un dico est indexé par des clefs.

Il est aussi possible de faire des dictionnaires de dictionnaire:

#+begin_src python
taille = {'bill': {'taille':1.70, 'poids':75},
          'bob': {'taille':1.85, 'poids':90 }}

return taille['bill']['poids']
#+end_src

#+RESULTS:
: 75

* [[id:8c4cd16e-6661-432d-a681-7dfbd5bcc62a][NumPy]]

Numpy est une librairie de Python fournissant un vecteur/matrice de n dimension et des méthodes/fonctions pour les créer et les manipuler.

* [[id:658786e3-79f5-472e-bcb4-4ce767d830da][Matplotlib]]

Une des bibliothèques de plot.

* [[id:a1f67fe2-36ce-44aa-b027-14256be6022f][Pandas]]
