:PROPERTIES:
:ID:       3f162ff8-3ce4-4299-9bdf-d45d75bada3e
:END:
#+title: #+title: Gyoza dumplings


 * Recette aprise via CORI et www.truetasteofthai.com


** Preparation

1. Prepare onion, garlic, ginger, cabbage, carrot, as well as your preferred protein.
2. Soak the dried mushrooms in warm water for at least 15-30 minutes. Finely chopped.
3. Non-stick pan is best to make Gyoza dumplings.


Ingredients: Making dough

2 cups all purpose flour
2/3 cup warm water

Ingredients: Filling

1 tsp cornstarch
3 tbsp water

Other ingredients:

2 tsp cooking oi
Soy sauce for dipping
Sriracha sauce

1. In a medium bowl, combine the flour and add a little bit of the warm water at a time until well-combined. Let the dough
rise for at least 15 minutes or more.
2. Roll out dough on a floured surface and knead until smooth. Divide the dough into 4 equal parts.
3. Roll out 1 piece of dough into a thin log and divide into 6 or 8 pieces, depending on the size of dumplings you want. Repeat
with the remaining dough portions.
4. Lightly flour the dough pieces and roll out 1 piece into a thin circle roughly 4-inches (10 cm) in diameter.
5. Mix all the ingredients f[fn:or the dipping in a small bowl. Set it aside.
6. To make the slurry, mix 1 tsp of cornstarch and 3 tbsp of water. Mix well and set it aside.
7. For the dumpling mix, combine your choice of protein with all chopped vegetables, soy sauce, salt, black pepper, and
sesame oil, in a large bowl and stir until well-incorporated.
8. Bring one wrapper at a time on your palm and wet the edge with water slightly. Place 1 tbsp of filling in the center of the
wrapper, fold as a half moon shape.
9. To seal the dumplings, start by folding the wrapper in half and then pinching shut the middle part. Next, fold in the side of
the dumpling wrapper closest to you to make a fold and then pinch it closed. Continue to the end of the dumpling,
pinching to seal the entire thing.
10. Heat a pan over medium high heat; add 2 tsp oil and place dumplings by giving them some room so they don’t touch each
other. Cook until the bottom of the dumplings turns brown.
11. Pour in the slurry to the skillet. Cover and let it cook for 5 to 6 minutes on low heat or until dumplings are fully cooked and
all the moisture evaporates.
12. Place a dish over the pan. Turn it over the whole thing. Carefully separate the dish and the skillet and serve the dumplings
immediately with the dipping sauce
